package main

import (
	"flag"
	"log"

	"github.com/metarsit/exchange"
)

func main() {
	var (
		key, secret string
		symbol      string
	)

	flag.StringVar(&key, "api", "", "API Key Generated by Crypto Exchange")
	flag.StringVar(&secret, "secret", "", "Secret Key Generated by Crypto Exchange")
	flag.StringVar(&symbol, "symbol", "", "Secret Key Generated by Crypto Exchange")
	flag.Parse()

	api, err := exchange.NewUserAPI(key, secret)
	if err != nil {
		log.Fatalf("Unable to create UserAPI Instance: %s", err.Error())
	}

	resp, err := api.CancelAllOrders(symbol)
	if err != nil {
		log.Fatalf("Unable to retrieve Account Balance: %s", err.Error())
	}

	if resp.Code != "0" {
		log.Fatalf("[%s] API Error %s", resp.Code, resp.Message)
	}

	log.Printf("Successfully cancel the all orders in %s", symbol)
}
